### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by cantt-s** [kristoisberg/samp-gps-plugin#4]
[20/04/2019 01:58:24] Loading plugin: GPS.so
[20/04/2019 01:58:24] Failed (/usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by plugins/GPS.so))

**Comment by Chaprnks** [comment]
Having this same issue, so maybe my progress can help you solve it. 

After checking whats included in the currently installed one, I noticed something:
![AVyeV9s](https://user-images.githubusercontent.com/6340970/59076505-6d395a00-88a4-11e9-9749-5a359cd5343b.png)
![BsiD6lK](https://user-images.githubusercontent.com/6340970/59076507-6f031d80-88a4-11e9-931e-f191284241bb.png)

It seems that the libstdc++ bundled with ubuntu xenial goes up to 3.4.21... one short of the minimum to run the plugin. I'm trying a few things & I'll reply once I get it figured out.

**Comment by Chaprnks** [comment]
It was actually a pretty easy fix. All you have to do is add the toolchain testing PPA & upgrade it :)

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
```
apt-get update
apt-get install gcc-4.9
apt-get upgrade libstdc++6
```
